export const SET_LOADING = "SET_LOADING";
export const SET_ALL_CITIES = "SET_ALL_CITIES";
export const SELECT_CITY = "SELECT_CITY";

export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const SET_ALL_CITY_RESTAURANTS = "SET_ALL_CITY_RESTAURANTS";
export const SET_RESULT_PAGE = "SET_RESULT_PAGE";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const FILTER_RESULTS = "FILTER_RESULTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
